name: Deploy Static Site
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy files to gh-pages
        run: |
          git checkout --orphan gh-pages
          cp -R frontend/* docs/
          git add .
          git commit -m "Deploy static site"
          git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
